### ISSUE TITLE
EventRepository를 변경하던 도중 궁금한 점이 있습니다

### ISSUE THREAD

**Issue by RbertKo** [DevelopDesignDayDay/attendance-spring-api#33]
# 내용
EventRepository에서 description을 nullable하게, type은 optional하게 변경해주었고, isDone은 `@ColumnDefault`를 이용하여 기본값을 `"False"`로 주었습니다.

그러다가 궁금한 점이 생겼습니다만,

 - description을 nullable, isDone을 기본값 false로 변경하였는데, 배포할 때 RDS에 migration이 자동으로 되나요~??
 - `lateDiffMinutes` 같은 property는 `@Column(name = "late_diff_min")` 와 같이 column명을 명시적으로 snake case를 전달해줬는데, `isDone`이나 그 외 property들도 변경해주면 될까요??

**Comment by 2rebi** [comment]
명시적으로 하면 좋고 저것들만 한 이유가 제가 원하는 내용의 컬럼명이 안떠서 그런거였어요 그리고 굳이 Column Default를 줄필요 없이 도메인 생성 하는 함수에서 기본값 조절하면 되니까 굳이 명시적으로 할필요 없습니다

**Comment by RbertKo** [comment]
@RebirthLee 굿. 그러면 컬럼명만 스네이크 케이스로 변경해도 괜찮을까요~??

**Comment by RbertKo** [comment]
@RebirthLee 답변 감사합니다~~~~~ 👍🏼
